### ISSUE TITLE
can't import terms without official units

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#113]
Currently, when I try to import an application term that has a unit that is not in the official list (i.e., one of the list options of "Unit Of Measure"), I just get an "[object Object]" error message.

Instead of getting an error message, I should be able to import anything I want to in the application unit field. If I try to import an unofficial unit for a BEDES composite term, I should still get an error message, but it should be more informative (e.g., "unrecognized unit for BEDES composite term").

**Comment by phgupta** [comment]
Make the application unit column free text.

**Comment by phgupta** [comment]
Fixed in f65ca90b03237ab0acd4ccee69edf6248f33a547

**Comment by TravisWalterLBNL** [comment]
Not fixed. I set the BEDES unit to TWh in my import file. Instead of telling me that's not an official unit, I was allowed to import the term and the unit was just ignored.

**Comment by phgupta** [comment]
But the BEDES unit should be in the official list right? It's only the application unit that's free-text.

**Comment by TravisWalterLBNL** [comment]
The BEDES unit should be from the official list (https://bedes.lbl.gov/bedes-online/unit-measure). If it isn't, an informative error message should be given.

The application unit should be a free text field.

**Comment by phgupta** [comment]
Fixed in 20c4105ea936fa1b23883aa7707e4e8aa66e87be

**Comment by TravisWalterLBNL** [comment]
Confirmed fixed.
