### ISSUE TITLE
unit in import file shouldn't be overwritten with blank BEDES unit

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#152]
Normally, when a new composite term is created during an import, it should inherit the unit of its final atomic term, and the unit specified in the import file is ignored. However, sometimes the unit of the final atomic term is blank. If this is the case, the unit in the import file should be used.

**Comment by TravisWalterLBNL** [comment]
To clarify: when this issues refers to a "blank" atomic term unit, it should really say "when the atomic term has Unit of Measure = Unknown".

**Comment by phgupta** [comment]
Fixed the "blank" part in 74dd5f01f68295c98bdb6ff8be06fe586f240fd0

**Comment by TravisWalterLBNL** [comment]
Not fixed. I imported a .csv then exported it and compared the results. Many rows had mismatched 'BEDES Term Unit'. It seems like there are two different problems here:

1. My composite term ended with the atomic term 'Quantity Intensity'. My import file had 'BEDES Term Unit' = 'count/ft2', but the export file had 'Unknown'. It looks like the unit of the final atomic term was used, but it should only overwrite if the unit isn't 'Unknown'.

2. My composite term ended with the atomic term 'Resource Cost'. The export file had 'BEDES Term Unit' = ''. Either the unit of the final atomic term isn't being used, or the atomic term has the wrong unit in the database. The correct unit for 'Resource Cost' is '$', and there shouldn't be any atomic terms with unit=''. They should all have a unit from the 'Unit Of Measure' list options.

**Comment by robHitchcock** [comment]
Confirmed not fixed in my NYSERDA import/export test. 

1. All composite terms with a defined import unit of measure, ending in an atomic term where unit = "Unknown" in the dictionary, were overwritten with "Unknown" in the export.

2. Composite terms ending in atomic terms that have a dictionary defined unit of "$" (e.g., "Cost", "Cost Savings", and "Rate Charge Value") have a blank unit of measure in the export. However, "Cost Effectiveness Value" results in an export unit of "Unknown" rather than the dictionary "$".

**Comment by phgupta** [comment]
Fixed in 45b447b3d88601c2694d42c8176a48d3487c4bb4

**Comment by TravisWalterLBNL** [comment]
Confirmed fixes.
